site:
  name: CausewaySoft
  site: 'https://causewaysoft.com'
  base: '/'
  trailingSlash: false

  googleSiteVerificationId: false

# Default SEO metadata
metadata:
  title:
    default: CausewaySoft
    template: '%s — CausewaySoft'
  description: "\U0001F680 CausewaySoft is an indie software studio crafting powerful web apps, PWA, mobile apps, and AI-powered solutions for startups, entrepreneurs, and visionary businesses. Born at the Giant's Causeway, Northern Ireland - Giant Apps for Giant Visionaries."
  robots:
    index: true
    follow: true
  openGraph:
    site_name: CausewaySoft
    images:
      - url: '~/assets/images/default.png'
        width: 1000
        height: 1000
    type: website 
  twitter:
    handle: '@causewaysoft'
    site: '@causewaysoft'
    cardType: summary_large_image

i18n:
  language: en
  textDirection: ltr

apps:
  blog:
    isEnabled: false
    postsPerPage: 6

    post:
      isEnabled: true
      permalink: '/%slug%' # Variables: %slug%, %year%, %month%, %day%, %hour%, %minute%, %second%, %category%
      robots:
        index: true

    list:
      isEnabled: true
      pathname: 'blog' # Blog main path, you can change this to "articles" (/articles)
      robots:
        index: true

    category:
      isEnabled: true
      pathname: 'category' # Category main path /category/some-category, you can change this to "group" (/group/some-category)
      robots:
        index: true

    tag:
      isEnabled: true
      pathname: 'tag' # Tag main path /tag/some-tag, you can change this to "topics" (/topics/some-category)
      robots:
        index: false

    isRelatedPostsEnabled: true
    relatedPostsCount: 4

analytics:
  vendors:
    googleAnalytics:
      id: "G-lookAtEnvVariables" #actual id is in the .env variables, to only collect analytics on actual build and not during development
      partytown: false

ui:
  theme: "dark" # Values: "system" | "light" | "dark" | "light:only" | "dark:only"
